import Head from "next/head";
import events from '../data/events.json';
import users from '../data/users.json';

export async function getServerSideProps(context) {
  return {
    props: {

    }
  };
}
export default function Page() {
  console.log(users);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello!
        <table>
          <tbody>
            {users.map((u) => {
              console.log(u);
              return (
                <tr>
                  <td>{u.distinct_ids}</td>
                  <td>{JSON.stringify(u.properties)}</td>
                  <td>{u.user_id}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </main>
      <style jsx>{`

    `}</style>
    </>
  );
}
