import Head from "next/head";
import events from '../data/events.json';
import { DataGrid } from '@mui/x-data-grid';
import Paper from '@mui/material/Paper';

export async function getServerSideProps(context) {
  return {
    props: {

    }
  };
}
export default function Page() {
  // Use a Set to track unique `distinct_id + timestamp` combinations
  const seen = new Set();
  const uniqueEvents = [];

  events.forEach(event => {
    const uniqueKey = `${event.event}-${event.distinct_id}-${event.timestamp}`;
    if (!seen.has(uniqueKey)) {
      seen.add(uniqueKey);
      uniqueEvents.push(event);
    }
  });

  const columns = [
    { field: 'distinct_id', headerName: 'Distinct IDs', width: 330 },
    { field: 'event', headerName: 'Event', width: 200 },
    { field: 'timestamp', headerName: 'Timestamp', width: 330 },
    {
      field: 'properties',
      headerName: 'Properties',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      width: 560,
      valueGetter: (value, row) => {
        return `${JSON.stringify(row.properties)}`
      },
    },
  ];

  const paginationModel = { page: 0, pageSize: 50 };
  return (
    <>
      <Head>
        <title>Justin Kuo Posthog Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Paper sx={{ height: 800, width: '100%' }}>
        <DataGrid
          getRowId={(row) => `${row.event}-${row.distinct_id}-${row.timestamp}`}
          rows={uniqueEvents.slice(0, 10)}
          columns={columns}
          checkboxSelection
          disableMultipleRowSelection
          sx={{ border: 0 }}
          initialState={{ pagination: { paginationModel } }}
          pageSizeOptions={[50, 100]}
        />
      </Paper>
      </main>
      <style jsx>{`

    `}</style>
    </>
  );
}
