import Head from "next/head";
import events from '../data/events.json';
import { DataGrid } from '@mui/x-data-grid';
import Paper from '@mui/material/Paper';

export async function getServerSideProps(context) {
  return {
    props: {

    }
  };
}
export default function Page() {
  // Using a Map to de-dupe
  const uniqueEvents = new Map();

  events.forEach((event) => {
    const key = `${event.distinct_id}-${event.event}`;

    if (!uniqueEvents.has(key) || new Date(event.timestamp) > new Date(uniqueEvents.get(key).timestamp)) {
      uniqueEvents.set(key, event);
    }
  });

  const deduplicatedEvents = Array.from(uniqueEvents.values());

  const columns = [
    { field: 'event', headerName: 'Event', width: 200 },
    { field: 'distinct_id', headerName: 'Distinct IDs', width: 330 },
    { field: 'timestamp', headerName: 'Timestamp', width: 330 },
    {
      field: 'properties',
      headerName: 'Properties',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      width: 560,
      valueGetter: (value, row) => {
        console.log(row);
        return `${JSON.stringify(row.properties)}`
      },
    },
  ];

  return (
    <>
      <Head>
        <title>Justin Kuo Posthog Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Paper sx={{ height: 800, width: '100%' }}>
        <DataGrid
          getRowId={(row) => row.distinct_id}
          rows={deduplicatedEvents}
          columns={columns}
          checkboxSelection
          sx={{ border: 0 }}
        />
      </Paper>
      </main>
      <style jsx>{`

    `}</style>
    </>
  );
}
