import Head from "next/head";
import users from '../data/users.json';
import { DataGrid } from '@mui/x-data-grid';
import Paper from '@mui/material/Paper';

export async function getServerSideProps(context) {
  return {
    props: {

    }
  };
}
export default function Page() {
  function createData({ user_id, distinct_ids, properties }) {
    return {
      userId: user_id,
      distinctIds: distinct_ids,
      properties: JSON.stringify(properties)
    }
  }

  const columns = [
    { field: 'user_id', headerName: 'User ID', width: 70 },
    { field: 'distinct_ids', headerName: 'Distinct IDs', width: 330 },
    {
      field: 'properties',
      headerName: 'Properties',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      width: 560,
      valueGetter: (value, row) => `${JSON.stringify(row)}`,
    },
  ];

  const paginationModel = { page: 0, pageSize: 100 };
  return (
    <>
      <Head>
        <title>Justin Kuo Posthog Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Paper sx={{ height: 800, width: '100%' }}>
        <DataGrid
          getRowId={(row) => row.user_id}
          rows={users}
          columns={columns}
          checkboxSelection
          sx={{ border: 0 }}
        />
      </Paper>
      </main>
      <style jsx>{`

    `}</style>
    </>
  );
}
